version: "3.7"
services:
  # servicio 1: La base de datos
  serv-postgres:
    image: postgres:9.6
    restart: always
    environment:
       POSTGRES_PASSWORD: postgres
       POSTGRES_USER: postgres
    ports:
      # puerto externo: puerto interno
      #- 33069:3306
      - 5433:5432
    volumes:
       - postgres:/var/lib/postgresql/data
       - ./postgresql/conf:/etc/postgresql/
    networks:
      laravel_prod_net:
        ipv4_address: 173.22.101.9

  # servicio 2: La instalación de apache
  serv-apache:
    build:
      # context: de donde se va a recuperar la configuración para la instalación
      context: ./
      dockerfile: dockerfile
    ports:
      - 8300:80
    volumes:
      - ./:/var/www/html
    networks:
      laravel_prod_net:
        ipv4_address: 173.22.101.10
    # depends_on indica que se cree primero la bd (servicio 1)
    depends_on:
      - serv-postgres

# se confirman los volumenes
volumes:
  postgres:      # carpeta E:/projects/docker/databases/mysql_3.7/schemas
networks:
  laravel_prod_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - 
          subnet: 173.22.101.0/24